=== vasvir/orthoeman/Content/XML/orthoeman.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://orthoeman.org/"
           elementFormDefault="qualified"
           xmlns="http://orthoeman.org/"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
        >


    <!-- definition of simple types -->
    <xs:simpleType name="IntegerType">
        <xs:restriction base="xs:integer"/>
    </xs:simpleType>

    <xs:simpleType name="WidgetTypeValues">
        <xs:restriction base="xs:string">
            <xs:enumeration value="text"/>
            <xs:enumeration value="image"/>
            <xs:enumeration value="quiz"/>
            <xs:enumeration value="video"/>
            <xs:enumeration value="input"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="VideoTypeValues">
        <xs:restriction base="xs:string">
            <xs:enumeration value="video/mp4"/>
            <xs:enumeration value="video/webm"/>
            <xs:enumeration value="video/ogg"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="YesNoValues">
        <xs:restriction base="xs:string">
            <xs:enumeration value="yes"/>
            <xs:enumeration value="no"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="UnconstrainedText">
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="preserve"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="GradeType">
        <xs:restriction base="xs:integer">
            <xs:maxInclusive value="100"/>
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- definition of complex types-->
    <xs:complexType name="PageType">
        <!-- <xs:sequence>
            <xs:element name="Widget" type="WidgetComplexType" minOccurs="2" maxOccurs="2"/>
        </xs:sequence> -->
        <xs:choice minOccurs="2" maxOccurs="2">
            <xs:element name="Text" type="UnconstrainedText"/>
            <xs:element name="Quiz" type="QuizType"/>
            <xs:element name="Image" type="ComplexImageType"/>
            <xs:element name="Video" type="VideoType"/>
            <xs:element name="RangeQuiz" type="InputValueType"/>
        </xs:choice>
        <xs:attribute name="title" type="xs:string" use="optional"/>
        <xs:attribute name="negativeGrade" type="GradeType" use="required"/>
        <xs:attribute name="positiveGrade" type="GradeType" use="required"/>
        <!-- <xs:attribute name="block" type="YesNoValues" use="required"/> -->
    </xs:complexType>

   <!-- <xs:complexType name="WidgetComplexType">
        <xs:choice>
            <xs:element name="Text" type="UnconstrainedText"/>
            <xs:group ref="QuizGroupElements"/>
            <xs:element name="Image" type="ComplexImageType"/>
            <xs:element name="Video" type="VideoType"/>
            <xs:element name="Input" type="InputValueType"/>
        </xs:choice>
        <xs:attribute name="type" type="WidgetTypeValues" use="required"/>
    </xs:complexType>   -->


    <xs:complexType name="ComplexImageType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="Circle" type="CircleType"/>
            <xs:element name="Ellipse" type="EllipseType"/>
            <xs:element name="Rectangle" type="RectType"/>
            <xs:element name="Polygon" type="PolygonType"/>
        </xs:choice>
        <xs:attribute name="showRegions" type="YesNoValues" use="required"/>
        <!-- <xs:attribute name="hotspots" type="YesNoValues" use="optional"/> -->
        <xs:attribute name="width" type="xs:integer" use="required"/>
        <xs:attribute name="height" type="xs:integer" use="required"/>
        <xs:attribute name="id" type="xs:integer" use="required"/>
        <!-- <xs:attribute name="maxSpots" type="xs:integer" use="optional"/> -->
        <xs:attribute name="enableTracking" type="YesNoValues" use="required"/>
    </xs:complexType>

    <xs:complexType name="QuizType">
        <xs:sequence>
            <xs:element name="Question" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Answer" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="isCorrect" type="YesNoValues" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="VideoType">
        <xs:sequence>
            <xs:element name="Source" minOccurs="1" maxOccurs="3">
                <xs:complexType>
                    <xs:attribute name="id" type="xs:integer" use="required"/>
                    <xs:attribute name="type" type="VideoTypeValues" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="InputValueType">
        <xs:all>
            <xs:element name="Question" type="UnconstrainedText" minOccurs="1" maxOccurs="1"/>
        </xs:all>
        <xs:attribute name="minValue" type="xs:float" use="required"/>
        <xs:attribute name="maxValue" type="xs:float" use="required"/>
    </xs:complexType>

    <xs:complexType name="CircleType">
        <xs:sequence>
            <xs:element name="Center" type="PointType" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="radius" type="xs:integer" use="required"/>
        <xs:attribute name="isHotSpot" type="YesNoValues" use="required"/>
    </xs:complexType>

    <xs:complexType name="EllipseType">
        <xs:sequence>
            <xs:element name="Center" type="PointType" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="isHotSpot" type="YesNoValues" use="required"/>
        <xs:attribute name="radiusX" type="xs:integer" use="required"/>
        <xs:attribute name="radiusY" type="xs:integer" use="required"/>
    </xs:complexType>

    <xs:complexType name="RectType">
        <xs:all>
            <xs:element name="Point" type="PointType"/>
        </xs:all>
        <xs:attribute name="isHotSpot" type="YesNoValues" use="required"/>
        <xs:attribute name="width" type="xs:integer" use="required" />
        <xs:attribute name="height" type="xs:integer" use="required" />
    </xs:complexType>

    <xs:complexType name="PolygonType">
        <xs:sequence>
            <xs:element name="Point" type="PointType" minOccurs="3" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="isHotSpot" type="YesNoValues" use="required"/>
    </xs:complexType>

    <xs:complexType name="PointType">
        <xs:attribute name="x" use="required" type="xs:integer"/>
        <xs:attribute name="y" use="required" type="xs:integer"/>
    </xs:complexType>


    <xs:group name="ImageDef">
        <xs:choice>
            <xs:element name="imageid" type="xs:integer"/>
            <xs:element name="imageuri" type="xs:anyURI"/>
        </xs:choice>
    </xs:group>



    <!--definition of elements-->

    <xs:element name="Lesson">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Abstract" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="Page" type="PageType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="title" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== vasvir/orthoeman/AuthoringTool/war/test.xml
<Lesson
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://orthoeman.iit.demokritos.gr/orthoeman.xsd"
	Id="lesson_id"
	Author="A. Authoropoulos"
	Title="Nice title">
	<Abstract>A very nice lesson. Really...</Abstract>
	<Page
		Title="opa"
		Grade="0.0"
		Blocked="false">
		<Widget Type="Image">
			<Image
				uri="http://127.0.0.1:8888/servlet.gupld?show=GWTU-012026485050169522&amp;gwt.codesvr=127.0.0.1:9997&amp;random=0.821230918143638">
				<Ellipse
					IsHotSpot="true"
					X="128"
					Y="161"
					Width="195"
					Height="132" />
				<Ellipse
					IsHotSpot="true"
					X="475"
					Y="182"
					A="281"
					B="262" />
				<Polygon IsHotSpot="false">
					<Point
						X="704"
						Y="369" />
					<Point
						X="348"
						Y="378" />
					<Point
						X="299"
						Y="136" />
					<Point
						X="632"
						Y="132" />
					<Point
						X="753"
						Y="217" />
					<Point
						X="704"
						Y="369" />
				</Polygon>
			</Image>
		</Widget>
		<Widget Type="Quiz">
			<Quiz>
				<Question>This statement is correct.</Question>
				<Answer IsCorrect="false">I don't think so</Answer>
				<Answer IsCorrect="false">really?</Answer>
				<Answer IsCorrect="false">Not sure</Answer>
				<Answer IsCorrect="true">Yes</Answer>
				<Answer IsCorrect="false">I don't know. I don't want to answer</Answer>
				<Answer IsCorrect="true">ela twra.???</Answer>
			</Quiz>
		</Widget>
	</Page>
	<Page
		Title="ouf"
		Grade="39.0"
		Blocked="true">
		<Widget Type="Video">
			<Video
				uri="servlet.gupld?show=GWTU-05880229170670555&amp;gwt.codesvr=127.0.0.1:9997&amp;random=0.14656990064111652" />
		</Widget>
		<Widget Type="Quiz">
			<Quiz>
				<Question></Question>
			</Quiz>
		</Widget>
	</Page>
</Lesson>

=== vasvir/orthoeman/Content/XML/XmlOrtho.xml
<?xml version="1.0" encoding="utf-8"?>
<Lesson xmlns="http://orthoeman.org/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" title="Template Title" xsi:schemaLocation="http://orthoeman.org/orthoeman.xsd">
  <Abstract>Little info describing the Lesson.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</Abstract>
    <Page grade="10">
            <Image id="3" enableTracking="no" showRegions="yes" width="480" height="640">
                <Polygon isHotSpot="yes">
                    <Point x="235" y="131"/>
                    <Point x="192" y="221"/>
                    <Point x="122" y="302"/>
                    <Point x="150" y="374"/>
                    <Point x="230" y="318"/>
                    <Point x="289" y="219"/>
                </Polygon>
            </Image>
            <Text>Identify ( Point)  the position of the fracture on the Xray</Text>
    </Page>
    <Page positiveGrade="30" negativeGrade="20">
            <Image id="4" enableTracking="yes" showRegions="no" width="482" height="214" />
            <RangeQuiz maxValue="410" minValue="390">
                <Question>Find the largest value of the force exerted on the forefoot:</Question>
            </RangeQuiz>
    </Page>
    <Page positiveGrade="30" negativeGrade="20">
            <Video>
                <Source id="2" type="video/mp4" />
                <Source id="3" type="video/webm" />
            </Video>
        <Quiz>
            <Question>Is the biomechanic behaviour consistent with the clinic of the patient?</Question>
            <Answer isCorrect="yes">Yes</Answer>
            <Answer isCorrect="no">No</Answer>
        </Quiz>
    </Page>

  <Page positiveGrade="30" negativeGrade="20">
      <Image id="5" enableTracking="no" showRegions="no" width="480" height="640" />
    <Quiz>
      <Question>Which is the type of the fracture?</Question>
      <Answer isCorrect="no">Femoral head</Answer>
      <Answer isCorrect="yes">Femoral neck, Pauwels  III</Answer>
      <Answer isCorrect="no">Trochanteric region</Answer>
      <Answer isCorrect="no">Femoral neck, Pauwels  II</Answer>
    </Quiz>
  </Page>
  <Page positiveGrade="30" negativeGrade="20">
      <Image id="9" showRegions="yes" enableTracking="no" width="480" height="640">
        <Circle isHotSpot="yes" radius="35">
          <Center x="189" y="152"/>
        </Circle>
          <Rectangle isHotSpot="yes" width="60" height="80">
              <Point x="5" y="5"/>
          </Rectangle>
        <Ellipse isHotSpot="yes" radiusX="40" radiusY="60">
          <Center x="416" y="498"/>
        </Ellipse>
      </Image>
      <Text>Point the two radiological findings concerning the 6.5 mm screw:( the 6.5 mm screw is the smallest one)</Text>
  </Page>
  <Page positiveGrade="30" negativeGrade="20">
      <Image id="11" enableTracking="no" showRegions="yes" width="480" height="640">
        <Circle isHotSpot="yes" radius="50">
          <Center x="133" y="173"/>
        </Circle>
      </Image>
      <Text>Point  the radiological finding concerning the dynamic screw:( the dynamic screw is the largest one).</Text>
  </Page>
  <Page positiveGrade="30" negativeGrade="20">
      <Image id="2" enableTracking="no" showRegions="yes" width="480" height="640">
        <Circle isHotSpot="no" radius="35">
          <Center x="189" y="152"/>
        </Circle>
        <Ellipse isHotSpot="no" radiusX="40" radiusY="60">
          <Center x="416" y="498"/>
        </Ellipse>
      </Image>
    <Quiz>
      <Question>Which of the following answers are correct:</Question>
      <Answer isCorrect="yes">The tip of the dynamic screw is situated much  too close to the superior border of the femoral head ( the dynamic screw is the largest one)</Answer>
      <Answer isCorrect="yes">The compression screw is not completely tightened, so compression is incomplete</Answer>
      <Answer isCorrect="no">The  thread of the dynamic screw is situated within the fracture</Answer>
      <Answer isCorrect="no">The dynamic screw screw is too short</Answer>
    </Quiz>
  </Page>
  <Page positiveGrade="30" negativeGrade="20">
      <Image id="2" enableTracking="no" showRegions="yes" width="1023" height="732">
        <Ellipse isHotSpot="yes" radiusX="70" radiusY="40">
          <Center x="446" y="407"/>
        </Ellipse>
      </Image>
      <Text>Identify (Point) the position of the patient Center of mass.</Text>
  </Page>
  <Page positiveGrade="30" negativeGrade="20">
      <Image id="3" enableTracking="no" showRegions="yes" width="1023" height="732" />
    <Quiz>
      <Question>Do you observe any anomaly in left-right dividing of the percentage of the body weight?</Question>
      <Answer isCorrect="no">No</Answer>
      <Answer isCorrect="no">yes, the distribution is higher for the left side</Answer>
      <Answer isCorrect="yes">yes, the distribution is higher for the right side</Answer>
    </Quiz>
  </Page>
  <Page positiveGrade="30" negativeGrade="20">
      <Image id="2" enableTracking="no" showRegions="yes" width="1024" height="734" />
    <Quiz>
      <Question>Please indicate the region that has an abnormal contact percentage:</Question>
      <Answer isCorrect="no">Rearfoot</Answer>
      <Answer isCorrect="yes">Midfoot</Answer>
      <Answer isCorrect="no">Forefoot</Answer>
    </Quiz>
  </Page>
</Lesson>
